package model.pojo;
// Generated Apr 4, 2017 8:17:45 PM by Hibernate Tools 4.3.1



/**
 * Authority generated by hbm2java
 */
public class Authority  implements java.io.Serializable {


     private int id;
     private Faculty faculty;
     private Major major;
     private String email;
     private String firstName;
     private String lastName;
     private String address;
     private String phoneNumber;
     private String role;

    public Authority() {
    }

    public Authority(int id, Faculty faculty, Major major, String email, String firstName, String lastName, String address, String phoneNumber, String role) {
       this.id = id;
       this.faculty = faculty;
       this.major = major;
       this.email = email;
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.phoneNumber = phoneNumber;
       this.role = role;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Faculty getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(Faculty faculty) {
        this.faculty = faculty;
    }
    public Major getMajor() {
        return this.major;
    }
    
    public void setMajor(Major major) {
        this.major = major;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


