package model.pojo;
// Generated Jun 5, 2017 1:35:22 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ChangeSectionForm generated by hbm2java
 */
public class ChangeSectionForm  implements java.io.Serializable {


     private ChangeSectionFormId id;
     private Student student;
     private int currentStage;
     private String status;
     private int requestOption;
     private String courseNumber;
     private String sectionNumber;
     private String requestMessage;
     private String deanApprovalSignature;
     private Date deanApprovalDate;

    public ChangeSectionForm() {
    }

	
    public ChangeSectionForm(ChangeSectionFormId id, Student student, int currentStage, String status, int requestOption, String courseNumber, String sectionNumber) {
        this.id = id;
        this.student = student;
        this.currentStage = currentStage;
        this.status = status;
        this.requestOption = requestOption;
        this.courseNumber = courseNumber;
        this.sectionNumber = sectionNumber;
    }
    public ChangeSectionForm(ChangeSectionFormId id, Student student, int currentStage, String status, int requestOption, String courseNumber, String sectionNumber, String requestMessage, String deanApprovalSignature, Date deanApprovalDate) {
       this.id = id;
       this.student = student;
       this.currentStage = currentStage;
       this.status = status;
       this.requestOption = requestOption;
       this.courseNumber = courseNumber;
       this.sectionNumber = sectionNumber;
       this.requestMessage = requestMessage;
       this.deanApprovalSignature = deanApprovalSignature;
       this.deanApprovalDate = deanApprovalDate;
    }
   
    public ChangeSectionFormId getId() {
        return this.id;
    }
    
    public void setId(ChangeSectionFormId id) {
        this.id = id;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public int getCurrentStage() {
        return this.currentStage;
    }
    
    public void setCurrentStage(int currentStage) {
        this.currentStage = currentStage;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public int getRequestOption() {
        return this.requestOption;
    }
    
    public void setRequestOption(int requestOption) {
        this.requestOption = requestOption;
    }
    public String getCourseNumber() {
        return this.courseNumber;
    }
    
    public void setCourseNumber(String courseNumber) {
        this.courseNumber = courseNumber;
    }
    public String getSectionNumber() {
        return this.sectionNumber;
    }
    
    public void setSectionNumber(String sectionNumber) {
        this.sectionNumber = sectionNumber;
    }
    public String getRequestMessage() {
        return this.requestMessage;
    }
    
    public void setRequestMessage(String requestMessage) {
        this.requestMessage = requestMessage;
    }
    public String getDeanApprovalSignature() {
        return this.deanApprovalSignature;
    }
    
    public void setDeanApprovalSignature(String deanApprovalSignature) {
        this.deanApprovalSignature = deanApprovalSignature;
    }
    public Date getDeanApprovalDate() {
        return this.deanApprovalDate;
    }
    
    public void setDeanApprovalDate(Date deanApprovalDate) {
        this.deanApprovalDate = deanApprovalDate;
    }




}


