package model.pojo;
// Generated May 3, 2017 1:11:18 AM by Hibernate Tools 4.3.1



/**
 * ChangeSectionForm generated by hbm2java
 */
public class ChangeSectionForm  implements java.io.Serializable {


     private ChangeSectionFormId id;
     private Student student;
     private int currentStage;
     private String status;
     private int requestOption;
     private String courseNumber;
     private String sectionNumber;
     private String requestMessage;
     private String authoritySignature;

    public ChangeSectionForm() {
    }

	
    public ChangeSectionForm(ChangeSectionFormId id, Student student, int currentStage, String status, int requestOption, String courseNumber, String sectionNumber) {
        this.id = id;
        this.student = student;
        this.currentStage = currentStage;
        this.status = status;
        this.requestOption = requestOption;
        this.courseNumber = courseNumber;
        this.sectionNumber = sectionNumber;
    }
    public ChangeSectionForm(ChangeSectionFormId id, Student student, int currentStage, String status, int requestOption, String courseNumber, String sectionNumber, String requestMessage, String authoritySignature) {
       this.id = id;
       this.student = student;
       this.currentStage = currentStage;
       this.status = status;
       this.requestOption = requestOption;
       this.courseNumber = courseNumber;
       this.sectionNumber = sectionNumber;
       this.requestMessage = requestMessage;
       this.authoritySignature = authoritySignature;
    }
   
    public ChangeSectionFormId getId() {
        return this.id;
    }
    
    public void setId(ChangeSectionFormId id) {
        this.id = id;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public int getCurrentStage() {
        return this.currentStage;
    }
    
    public void setCurrentStage(int currentStage) {
        this.currentStage = currentStage;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public int getRequestOption() {
        return this.requestOption;
    }
    
    public void setRequestOption(int requestOption) {
        this.requestOption = requestOption;
    }
    public String getCourseNumber() {
        return this.courseNumber;
    }
    
    public void setCourseNumber(String courseNumber) {
        this.courseNumber = courseNumber;
    }
    public String getSectionNumber() {
        return this.sectionNumber;
    }
    
    public void setSectionNumber(String sectionNumber) {
        this.sectionNumber = sectionNumber;
    }
    public String getRequestMessage() {
        return this.requestMessage;
    }
    
    public void setRequestMessage(String requestMessage) {
        this.requestMessage = requestMessage;
    }
    public String getAuthoritySignature() {
        return this.authoritySignature;
    }
    
    public void setAuthoritySignature(String authoritySignature) {
        this.authoritySignature = authoritySignature;
    }




}


