package model.pojo;
// Generated Jun 5, 2017 1:35:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Faculty generated by hbm2java
 */
public class Faculty  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set students = new HashSet(0);
     private Set authorities = new HashSet(0);
     private Set majors = new HashSet(0);

    public Faculty() {
    }

	
    public Faculty(String name) {
        this.name = name;
    }
    public Faculty(String name, Set students, Set authorities, Set majors) {
       this.name = name;
       this.students = students;
       this.authorities = authorities;
       this.majors = majors;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }
    public Set getAuthorities() {
        return this.authorities;
    }
    
    public void setAuthorities(Set authorities) {
        this.authorities = authorities;
    }
    public Set getMajors() {
        return this.majors;
    }
    
    public void setMajors(Set majors) {
        this.majors = majors;
    }




}


