package model.pojo;
// Generated May 3, 2017 2:10:40 AM by Hibernate Tools 4.3.1



/**
 * FormType generated by hbm2java
 */
public class FormType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String formPath;
     private String tableName;
     private int maxStage;
     private String flow;

    public FormType() {
    }

    public FormType(String name, String formPath, String tableName, int maxStage, String flow) {
       this.name = name;
       this.formPath = formPath;
       this.tableName = tableName;
       this.maxStage = maxStage;
       this.flow = flow;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFormPath() {
        return this.formPath;
    }
    
    public void setFormPath(String formPath) {
        this.formPath = formPath;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public int getMaxStage() {
        return this.maxStage;
    }
    
    public void setMaxStage(int maxStage) {
        this.maxStage = maxStage;
    }
    public String getFlow() {
        return this.flow;
    }
    
    public void setFlow(String flow) {
        this.flow = flow;
    }




}


