package model.pojo;
// Generated Jun 5, 2017 1:35:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Major generated by hbm2java
 */
public class Major  implements java.io.Serializable {


     private Integer id;
     private Faculty faculty;
     private String name;
     private Set students = new HashSet(0);
     private Set authorities = new HashSet(0);

    public Major() {
    }

	
    public Major(Faculty faculty, String name) {
        this.faculty = faculty;
        this.name = name;
    }
    public Major(Faculty faculty, String name, Set students, Set authorities) {
       this.faculty = faculty;
       this.name = name;
       this.students = students;
       this.authorities = authorities;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Faculty getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(Faculty faculty) {
        this.faculty = faculty;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }
    public Set getAuthorities() {
        return this.authorities;
    }
    
    public void setAuthorities(Set authorities) {
        this.authorities = authorities;
    }




}


