package model.pojo;
// Generated Jun 5, 2017 1:35:22 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PetitionFormId generated by hbm2java
 */
public class PetitionFormId  implements java.io.Serializable {


     private Date submitTime;
     private int studentId;

    public PetitionFormId() {
    }

    public PetitionFormId(Date submitTime, int studentId) {
       this.submitTime = submitTime;
       this.studentId = studentId;
    }
   
    public Date getSubmitTime() {
        return this.submitTime;
    }
    
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PetitionFormId) ) return false;
		 PetitionFormId castOther = ( PetitionFormId ) other; 
         
		 return ( (this.getSubmitTime()==castOther.getSubmitTime()) || ( this.getSubmitTime()!=null && castOther.getSubmitTime()!=null && this.getSubmitTime().equals(castOther.getSubmitTime()) ) )
 && (this.getStudentId()==castOther.getStudentId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSubmitTime() == null ? 0 : this.getSubmitTime().hashCode() );
         result = 37 * result + this.getStudentId();
         return result;
   }   


}


