package model.pojo;
// Generated Apr 4, 2017 8:17:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PetitionFormId generated by hbm2java
 */
public class PetitionFormId  implements java.io.Serializable {


     private int studentRequestStudentId;
     private int studentRequestFormTypeId;
     private Date studentRequestSubmitTime;

    public PetitionFormId() {
    }

    public PetitionFormId(int studentRequestStudentId, int studentRequestFormTypeId, Date studentRequestSubmitTime) {
       this.studentRequestStudentId = studentRequestStudentId;
       this.studentRequestFormTypeId = studentRequestFormTypeId;
       this.studentRequestSubmitTime = studentRequestSubmitTime;
    }
   
    public int getStudentRequestStudentId() {
        return this.studentRequestStudentId;
    }
    
    public void setStudentRequestStudentId(int studentRequestStudentId) {
        this.studentRequestStudentId = studentRequestStudentId;
    }
    public int getStudentRequestFormTypeId() {
        return this.studentRequestFormTypeId;
    }
    
    public void setStudentRequestFormTypeId(int studentRequestFormTypeId) {
        this.studentRequestFormTypeId = studentRequestFormTypeId;
    }
    public Date getStudentRequestSubmitTime() {
        return this.studentRequestSubmitTime;
    }
    
    public void setStudentRequestSubmitTime(Date studentRequestSubmitTime) {
        this.studentRequestSubmitTime = studentRequestSubmitTime;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PetitionFormId) ) return false;
		 PetitionFormId castOther = ( PetitionFormId ) other; 
         
		 return (this.getStudentRequestStudentId()==castOther.getStudentRequestStudentId())
 && (this.getStudentRequestFormTypeId()==castOther.getStudentRequestFormTypeId())
 && ( (this.getStudentRequestSubmitTime()==castOther.getStudentRequestSubmitTime()) || ( this.getStudentRequestSubmitTime()!=null && castOther.getStudentRequestSubmitTime()!=null && this.getStudentRequestSubmitTime().equals(castOther.getStudentRequestSubmitTime()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStudentRequestStudentId();
         result = 37 * result + this.getStudentRequestFormTypeId();
         result = 37 * result + ( getStudentRequestSubmitTime() == null ? 0 : this.getStudentRequestSubmitTime().hashCode() );
         return result;
   }   


}


