package model.pojo;
// Generated Jun 5, 2017 1:35:22 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PetitionForm generated by hbm2java
 */
public class PetitionForm  implements java.io.Serializable {


     private PetitionFormId id;
     private Student student;
     private int currentStage;
     private String status;
     private int requestOption;
     private String requestMessage;
     private String requestReason;
     private String deanApprovalSignature;
     private Date deanApprovalDate;
     private String advisorApprovalSignature;
     private Date advisorApprovalDate;

    public PetitionForm() {
    }

	
    public PetitionForm(PetitionFormId id, Student student, int currentStage, String status, int requestOption) {
        this.id = id;
        this.student = student;
        this.currentStage = currentStage;
        this.status = status;
        this.requestOption = requestOption;
    }
    public PetitionForm(PetitionFormId id, Student student, int currentStage, String status, int requestOption, String requestMessage, String requestReason, String deanApprovalSignature, Date deanApprovalDate, String advisorApprovalSignature, Date advisorApprovalDate) {
       this.id = id;
       this.student = student;
       this.currentStage = currentStage;
       this.status = status;
       this.requestOption = requestOption;
       this.requestMessage = requestMessage;
       this.requestReason = requestReason;
       this.deanApprovalSignature = deanApprovalSignature;
       this.deanApprovalDate = deanApprovalDate;
       this.advisorApprovalSignature = advisorApprovalSignature;
       this.advisorApprovalDate = advisorApprovalDate;
    }
   
    public PetitionFormId getId() {
        return this.id;
    }
    
    public void setId(PetitionFormId id) {
        this.id = id;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public int getCurrentStage() {
        return this.currentStage;
    }
    
    public void setCurrentStage(int currentStage) {
        this.currentStage = currentStage;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public int getRequestOption() {
        return this.requestOption;
    }
    
    public void setRequestOption(int requestOption) {
        this.requestOption = requestOption;
    }
    public String getRequestMessage() {
        return this.requestMessage;
    }
    
    public void setRequestMessage(String requestMessage) {
        this.requestMessage = requestMessage;
    }
    public String getRequestReason() {
        return this.requestReason;
    }
    
    public void setRequestReason(String requestReason) {
        this.requestReason = requestReason;
    }
    public String getDeanApprovalSignature() {
        return this.deanApprovalSignature;
    }
    
    public void setDeanApprovalSignature(String deanApprovalSignature) {
        this.deanApprovalSignature = deanApprovalSignature;
    }
    public Date getDeanApprovalDate() {
        return this.deanApprovalDate;
    }
    
    public void setDeanApprovalDate(Date deanApprovalDate) {
        this.deanApprovalDate = deanApprovalDate;
    }
    public String getAdvisorApprovalSignature() {
        return this.advisorApprovalSignature;
    }
    
    public void setAdvisorApprovalSignature(String advisorApprovalSignature) {
        this.advisorApprovalSignature = advisorApprovalSignature;
    }
    public Date getAdvisorApprovalDate() {
        return this.advisorApprovalDate;
    }
    
    public void setAdvisorApprovalDate(Date advisorApprovalDate) {
        this.advisorApprovalDate = advisorApprovalDate;
    }




}


