package model.pojo;
// Generated Apr 4, 2017 8:17:45 PM by Hibernate Tools 4.3.1



/**
 * PetitionForm generated by hbm2java
 */
public class PetitionForm  implements java.io.Serializable {


     private PetitionFormId id;
     private StudentRequest studentRequest;
     private int requestOption;
     private String requestMessage;
     private String requestReason;
     private String advisorSignature;

    public PetitionForm() {
    }

	
    public PetitionForm(StudentRequest studentRequest, int requestOption) {
        this.studentRequest = studentRequest;
        this.requestOption = requestOption;
    }
    public PetitionForm(StudentRequest studentRequest, int requestOption, String requestMessage, String requestReason, String advisorSignature) {
       this.studentRequest = studentRequest;
       this.requestOption = requestOption;
       this.requestMessage = requestMessage;
       this.requestReason = requestReason;
       this.advisorSignature = advisorSignature;
    }
   
    public PetitionFormId getId() {
        return this.id;
    }
    
    public void setId(PetitionFormId id) {
        this.id = id;
    }
    public StudentRequest getStudentRequest() {
        return this.studentRequest;
    }
    
    public void setStudentRequest(StudentRequest studentRequest) {
        this.studentRequest = studentRequest;
    }
    public int getRequestOption() {
        return this.requestOption;
    }
    
    public void setRequestOption(int requestOption) {
        this.requestOption = requestOption;
    }
    public String getRequestMessage() {
        return this.requestMessage;
    }
    
    public void setRequestMessage(String requestMessage) {
        this.requestMessage = requestMessage;
    }
    public String getRequestReason() {
        return this.requestReason;
    }
    
    public void setRequestReason(String requestReason) {
        this.requestReason = requestReason;
    }
    public String getAdvisorSignature() {
        return this.advisorSignature;
    }
    
    public void setAdvisorSignature(String advisorSignature) {
        this.advisorSignature = advisorSignature;
    }




}


