package model.pojo;
// Generated Apr 4, 2017 8:17:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StudentRequestId generated by hbm2java
 */
public class StudentRequestId  implements java.io.Serializable {


     private int studentId;
     private int formTypeId;
     private Date submitTime;

    public StudentRequestId() {
    }

    public StudentRequestId(int studentId, int formTypeId, Date submitTime) {
       this.studentId = studentId;
       this.formTypeId = formTypeId;
       this.submitTime = submitTime;
    }
   
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public int getFormTypeId() {
        return this.formTypeId;
    }
    
    public void setFormTypeId(int formTypeId) {
        this.formTypeId = formTypeId;
    }
    public Date getSubmitTime() {
        return this.submitTime;
    }
    
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentRequestId) ) return false;
		 StudentRequestId castOther = ( StudentRequestId ) other; 
         
		 return (this.getStudentId()==castOther.getStudentId())
 && (this.getFormTypeId()==castOther.getFormTypeId())
 && ( (this.getSubmitTime()==castOther.getSubmitTime()) || ( this.getSubmitTime()!=null && castOther.getSubmitTime()!=null && this.getSubmitTime().equals(castOther.getSubmitTime()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStudentId();
         result = 37 * result + this.getFormTypeId();
         result = 37 * result + ( getSubmitTime() == null ? 0 : this.getSubmitTime().hashCode() );
         return result;
   }   


}


